language: java
dist: trusty
jdk:
  - oraclejdk8
install: 
  - git fetch origin release/hive-1.x
  - git fetch origin release/hive-2.x
script:
  - ./release.sh
deploy:
  provider: releases
  api_key:
    secure: GltGSpyk4fXhE7KSuU1X1eoyubYA51JbjiiXgpPz02kJDmGBP8K7J4myM5qUthyu/pXs4wD8HeQKpQE2i8C5jCI0dLLC5qt3WfXOHJ80TmQWJD3JNyEmjFNp8vWHpHrO2Pd9Z3tS719jesegEGpFMiY1JOG2xIJfPJkBojc0cTbXWoffx6TZ3Nt3r4L57poS3nfxI4+siDpIii6A7zrLOGGuBUbU2zFY4jvEOFeBmisz/E8qXEtHQnFhNtrqJ5XWEazqgyA52YbiIZJA4DravSVJpxoUa5YZjtIOhEm7gKERe+2q6fK1rH2XBL03pg2cQ1CFfYC60RKucOOw0dMwwk7rIfsrNfEZDom20UfA4dtHFZY9BeAASAeDvPrgwa5aZFpGR+KONnPW/7i4zc6f3CP4rLrxJtyc5sd17WfyrxJ01GY/6jsIauRJRMq0geoBgM2fTlBFzQ1mbTRvulJ4K0oXqfGcCED27v0XZa3I0rwuT1QmFoRic9xp/X6MHcBEwUB6YCZGx8Vg2XlwxrW9Fy/1bnULDrFX8fr9ySO7ijRl9WHVcOY18EL5auXsP48KtnMDurkB6qKXqtcQYWyaWtxIl1Alk8XIhPAaL7U2hO8MMx1hZd9xWjPLoYqPuHcQMrP93Sy0G2212lfwvXWxXVhZAoJah4u4QjK6yisYflY=
  file_glob: false
  file:
    - mma-hive-1.x-release.tar.gz
    - mma-hive-2.x-release.tar.gz
  skip_cleanup: true
  on:
    tags: true
